name: Generate ASCII

on: push

jobs:
  generate_ascii:
    runs-on: ubuntu-latest
    name: Generate ASCII
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: list file
      run: ls -lrt

    - name: Executing shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
