name: Matrix configuration

on: 
    push:
    workflow_dispatch: 

jobs:
    deploy:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            images: [hello-world]
        runs-on: ${{ matrix.os }}
        name: Deploy
        steps:
          - name: Echo Docker detail
            run: docker info

          - name: Run Image on ${{ matrix.os }}
            run: docker run ${{ matrix.images }}